trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: mkdir -p $(Build.SourcesDirectory)/Releases
  displayName: 'Create Releases directory'
  
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/*.csproj'
    arguments: '--output $(Build.SourcesDirectory)/Releases -r win10-x64 --self-contained true -p:PublishSingleFile=true -p:EnableCompressionInSingleFile=true -p:PublishTrimmed=true'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/Releases'
    ArtifactName: 'EntityMetadata'
    publishLocation: 'Container'